# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: portefaix-C0002
  annotations:
    policies.kyverno.io/title: Container must set liveness probe
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Container
    policies.kyverno.io/description: >-
      Liveness probe need to be configured to correctly manage a pods
      lifecycle during deployments, restarts, and upgrades. For each pod,
      a periodic `livenessProbe` is performed by the kubelet to determine
      if the pod's containers are running or need to be restarted
spec:
  validationFailureAction: audit
  rules:
  - name: validate-liveness-probe
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Liveness probe is required."
      pattern:
        spec:
          containers:
          - livenessProbe:
              periodSeconds: "?*"
