# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

# Labels for action/labeler

######################################
# Label area/xxx

area/cel:
- changed-files:
  - any-glob-to-any-file: cel/**

area/kubewarden:
- changed-files:
  - any-glob-to-any-file: kubewarden/**

area/kyverno:
- changed-files:
  - any-glob-to-any-file: kyverno/**

area/opa:
- changed-files:
  - any-glob-to-any-file: opa/**

area/github:
- changed-files:
  - any-glob-to-any-file: .github/**

######################################
# Label krm/xxx

krm/gcp-config-connector:
- changed-files:
  - any-glob-to-any-file: krm/kcc/**

krm/aws-controllers-k8s:
- changed-files:
  - any-glob-to-any-file: krm/ack/**

krm/azure-service-operator:
- changed-files:
  - any-glob-to-any-file: krm/aso/**

krm/crossplane:
- changed-files:
  - any-glob-to-any-file: krm/crossplane/**
