# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
_extends: .github:.github/settings.yml

# repo-specific settings

repository:
  name: "portefaix-policies"
  description: "Portefaix Policies"
  topics: portefaix, Kubernetes, policy-as-code, kyverno, opa, kubewarden

labels:

## CLOUD PROVIDERS

- name: "cloud/gcp"
  description: "Cloud Provider / Google Cloud Provider"
  color: "068082"

- name: "cloud/aws"
  description: "Cloud Provider / Amazon AWS"
  color: "068082"

- name: "cloud/azure"
  description: "Cloud Provider / Microsoft Azure"
  color: "068082"

- name: "cloud/scaleway"
  description: "Cloud Provider / Scaleway"
  color: "068082"

- name: "cloud/oci"
  description: "Cloud Provider / OCI"
  color: "068082"

- name: "cloud/ibmcloud"
  description: "Cloud Provider / IBMCloud"
  color: "068082"

- name: "cloud/digitalocean"
  description: "Cloud Provider / Digital Ocean"
  color: "068082"

- name: "cloud/alicloud"
  description: "Cloud Provider / Alicloud"
  color: "068082"

- name: "cloud/exoscale"
  description: "Cloud Provider / Exoscale"
  color: "068082"

- name: "cloud/homelab"
  description: "Cloud Provider / Homelab"
  color: "068082"

- name: "cloud/cicd"
  description: "Cloud Provider / CICD"
  color: "068082"

- name: "cloud/vultr"
  description: "Cloud Provider / Vultr"
  color: "068082"

- name: "cloud/civo"
  description: "Cloud Provider / Civo"
  color: "068082"

## AREA

- name: "area/cel"
  description: "CEL"
  color: "cc317c"

- name: "area/opa"
  description: "Open Policy Agent"
  color: "cc317c"

- name: "area/kyverno"
  description: "Kyverno"
  color: "cc317c"

- name: "area/kubewarden"
  description: "Kubewarden"
  color: "cc317c"
