# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
        args:
        - '--allow-multiple-documents'
        exclude: mkdocs.yml
    -   id: check-added-large-files
- repo: local
  hooks:
  - id: hawkeye
    name: "📄 Hawkeye / Insert license header"
    entry: bash -c 'hawkeye format'
    language: system
    pass_filenames: true
    files: \.*$
    args: []
- repo: local
  hooks:
  - id: dprint
    name: "📝 Dprint / Formatting"
    entry: bash -c 'dprint fmt'
    language: system
    pass_filenames: true
    files: \.*$
    args: []
# -   repo: https://github.com/Lucas-C/pre-commit-hooks
#     rev: v1.3.1
#     hooks:
#     -   id: insert-license
#         files:  (Makefile|\.mk|\.yaml|\.yml|\.rego|\.toml|\.sh)
#         args:
#         - --license-filepath
#         - LICENSE
#         - --remove-header
# TODO: https://github.com/dprint/dprint/issues/442
# - repo: https://github.com/spinergie/pre-commit-dprint
#   rev: v0.42.5
#   hooks:
#   - id: dprint
#     pass_filenames: false
- repo: https://github.com/anderseknert/pre-commit-opa
  rev: v1.5.0
  hooks:
  - id: opa-fmt
  - id: opa-check
    args: ['opa']
  - id: opa-test
    args: ['opa']
#   - id: conftest-test
#     args: ['--policy', 'opa']
  - id: conftest-verify
    args: ['--data', 'opa/lib', '--policy', 'opa']
# - repo: https://github.com/kyverno/pre-commit-hook
#   rev: v1.0.0
#   hooks:
#   - id: kyverno-validate
#     name: Kyverno validate
#     args: [./kyverno]
#     verbose: true
#   - id: kyverno-test
#     name: Kyverno test
#     args: ["./kyverno"]
