# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: portefaix-C0003
  annotations:
    policies.kyverno.io/title: Container must set readiness probe
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/severity: high
    policies.kyverno.io/subject: Container
    policies.kyverno.io/description: >-
      Readiness probe need to be configured to correctly manage a pods
      lifecycle during deployments, restarts, and upgrades. For each pod, a
      `readinessProbe` is used by services and deployments to determine if
      the pod is ready to receive network traffic.
spec:
  validationFailureAction: audit
  rules:
  - name: validate-readiness-probe
    match:
      resources:
        kinds:
        - Pod
    validate:
      message: "Readiness probe is required."
      pattern:
        spec:
          containers:
          - readinessProbe:
              periodSeconds: "?*"
