# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicy
metadata:
  name: c0008.container.portefaix.xyz
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["pods"]
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["deployments","replicasets","daemonsets","statefulsets"]
    - apiGroups:   ["batch"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["jobs","cronjobs"]
  validations:
    - expression: >
        object.kind != 'Pod' || object.spec.containers.all(container,
        has(container.resources) &&
        has(container.resources.requests) &&
        has(container.resources.requests.cpu) &&
        has(container.resources.requests.memory) &&
        has(container.resources.limits) &&
        has(container.resources.limits.memory))
      message: "CPU and memory resource requests and limits are required."

    - expression: >
        ['Deployment','ReplicaSet','DaemonSet','StatefulSet','Job'].all(kind, object.kind != kind) || object.spec.template.spec.containers.all(container,
        has(container.resources) &&
        has(container.resources.requests) &&
        has(container.resources.requests.cpu) &&
        has(container.resources.requests.memory) &&
        has(container.resources.limits) &&
        has(container.resources.limits.memory))
      message: "CPU and memory resource requests and limits are required."

    - expression: >
        object.kind != 'CronJob' || object.spec.jobTemplate.spec.containers.all(container,
        has(container.resources) &&
        has(container.resources.requests) &&
        has(container.resources.requests.cpu) &&
        has(container.resources.requests.memory) &&
        has(container.resources.limits) &&
        has(container.resources.limits.memory))
      message: "CPU and memory resource requests and limits are required."
  auditAnnotations:
  - key: "container-resources-requests-limits"
    valueExpression: "CPU and Memory resource requests and limits are required"
---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: c0008.container.portefaix.xyz
spec:
  policyName: c0008.container.portefaix.xyz
  validationActions: [Warn, Audit]