# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: portefaix-C0001
  annotations:
    policies.kyverno.io/title: Docker images used by control plane pods are correctly signed
    policies.kyverno.io/category: Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: Container
    policies.kyverno.io/description: >-
      The ':latest' tag is mutable and can lead to unexpected errors if the
      image changes. A best practice is to use an immutable tag that maps to
      a specific version of an application pod.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: verify-k8s-images
      match:
        any:
          - resources:
              kinds:
                - Pod
      verifyImages:
      # verify kube-* and coredns/* images
      - imageReferences:
        - registry.k8s.io/kube-*
        - registry.k8s.io/coredns/*
        verifyDigest: false
        required: false
        mutateDigest: false
        attestors:
        - entries:
          - keyless:
              issuer: https://accounts.google.com
              subject: krel-trust@k8s-releng-prod.iam.gserviceaccount.com
              rekor:
                url: https://rekor.sigstore.dev
      # verify etcd:* images
      - imageReferences:
        - registry.k8s.io/etcd:*
        verifyDigest: false
        required: false
        mutateDigest: false
        attestors:
        - entries:
          - keyless:
              issuer: https://accounts.google.com
              subject: k8s-infra-gcr-promoter@k8s-artifacts-prod.iam.gserviceaccount.com
              rekor:
                url: https://rekor.sigstore.dev
