# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: portefaix-M0003
  annotations:
    policies.kyverno.io/title: Metadata should have portefaix.xyz labels
    policies.kyverno.io/category: Portefaix
    policies.kyverno.io/severity: low
    policies.kyverno.io/subject: Metadata
    policies.kyverno.io/description: >-
      Metadata should have Portefaix labels:
      Labels are:
        - portefaix.xyz/version
spec:
  validationFailureAction: audit
  rules:
  - name: check-for-portefaix.xyz-labels
    match:
      resources:
        kinds:
        - "ConfigMap"
        - "Secret"
        - "Pod"
        - "Deployment"
        - "DaemonSet"
        - "StatefulSet"
        - "Service"
        - "Job"
        - "CronJob"
        - "Role"
        - "RoleBinding"
        - "ClusterRole"
        - "ClusterRoleBinding"
        - "ServiceAccount"
        - "Ingress"
        - "IngressClass"
        - "NetworkPolicy"
        - "PodDisruptionBudget"
        - "StorageClass"
    validate:
      message: "portefaix.xyz labels is required."
      pattern:
        metadata:
          labels:
            portefaix.xyz/version: "?*"
