# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-ok
  namespace: default
  labels:
    portefaix.xyz/version: v1.0.0
spec:
  containers:
  - name: nginx
    image: nginx:1.12
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-ko
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:1.12
