# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicy
metadata:
  name: m0001.metadata.portefaix.xyz
spec:
  failurePolicy: Fail
  matchConstraints:
    resourceRules:
    # - apiGroups:   [""]
    #   apiVersions: ["v1"]
    #   operations:  ["CREATE", "UPDATE"]
    #   resources:   ["namespaces"]
    - apiGroups:   [""]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["pods"]
    - apiGroups:   ["apps"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["deployments","replicasets","daemonsets","statefulsets"]
    - apiGroups:   ["batch"]
      apiVersions: ["v1"]
      operations:  ["CREATE", "UPDATE"]
      resources:   ["jobs","cronjobs"]
  validations:
  - expression: >
      has(object.metadata.labels) &&
      'app.kubernetes.io/name' in object.metadata.labels &&
      'app.kubernetes.io/instance' in object.metadata.labels &&
      'app.kubernetes.io/version' in object.metadata.labels &&
      'app.kubernetes.io/component' in object.metadata.labels &&
      'app.kubernetes.io/part-of' in object.metadata.labels &&
      'app.kubernetes.io/managed-by' in object.metadata.labels
    message: "Kubernetes recommended labels is required."
  auditAnnotations:
  - key: "metadata-kubernetes-recommended-labels"
    valueExpression: "Kubernetes recommended labels is required"
---
apiVersion: admissionregistration.k8s.io/v1alpha1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: m0001.container.portefaix.xyz
spec:
  policyName: m0001.container.portefaix.xyz
  validationActions: [Warn, Audit]