# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: registryconfiguration.policy.portefaix.xyz
  annotations:
    admission.kubernetes.io/is-policy-configuration-definition: "true"
spec:
  group: policy.portefaix.xyz
  names:
    kind: RegistryConfiguration
    plural: registryconfigurations
    singular: registryconfiguration
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        description: |-
          RegistryConfiguration configures the Portefaix policy concerning public registries and untrusted registries
        type: object
        properties:
          spec:
            description: |-
              RegistryConfigurationSpec is a specification of the desired behavior of the
              Registry Configuration configuration.
            type: object
            properties:
              publicRegistries:
                description: |-
                  List of authorized public registries
                items:
                  type: string
                type: array
              untrustedRegistries:
                description: |-
                  List of untrusted registries
                items:
                  type: string
                type: array
    served: true
    storage: true
  scope: Cluster
