# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-ok
  labels:
    app: myapp
spec:
  containers:
  - name: goproxy
    image: ghcr.io/goproxy:0.1
    ports:
    - containerPort: 8080
    readinessProbe:
      tcpSocket:
        port: 8080
      periodSeconds: 10
---
apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-ko
  labels:
    app: myapp
spec:
  containers:
  - name: goproxy
    image: quay.io/goproxy:0.1
    ports:
    - containerPort: 8080
    livenessProbe:
      tcpSocket:
        port: 8080
      periodSeconds: 10
