# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

name: Kyverno / Tests

on:
  push:
    branches:
      - master
    paths:
      - "kyverno/**"
  pull_request:
    branches:
      - master
    paths:
      - "kyverno/**"

jobs:
  kyverno:
    runs-on: ubuntu-latest
    name: Run kyverno
    steps:
    - name: Checkout
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Validate policies
      uses: gbaeke/kyverno-cli@v1
      with:
        command: |
          kyverno validate ./kyverno

    - name: Test policies
      uses: gbaeke/kyverno-cli@v1
      with:
        command: |
          kyverno test ./kyverno
