# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

name: Open Policy Agent / Tests

on:
  push:
    branches:
      - master
    paths:
      - "opa/**"
  pull_request:
    branches:
      - master
    paths:
      - "opa/**"

jobs:
  opa:
    name: opa test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: OPA Test
      uses: petroprotsakh/opa-test-action@v2.1
      with:
        options: -f pretty -v
        tests: |
          opa
