# SPDX-FileCopyrightText: Copyright (C) Nicolas Lamirault <nicolas.lamirault@gmail.com>
# SPDX-License-Identifier: Apache-2.0

name: Open Policy Agent / Tests

on:
  push:
    branches:
      - master
    paths:
      - "opa/**"
  pull_request:
    branches:
      - master
    paths:
      - "opa/**"

jobs:
  opa:
    name: opa test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: OPA Test
      uses: petroprotsakh/opa-test-action@v2.1
      with:
        options: -f pretty -v
        tests: |
          opa
